"""Change recipe fields to text

Revision ID: 4b42e8bf31a6
Revises: c35cca99f46c
Create Date: 2026-05-13 10:26:49.831637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b42e8bf31a6'
down_revision = 'c35cca99f46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('ingredients',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
        batch_op.alter_column('ingredients',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
