"""add image_filename to recipe model

Revision ID: 710a4b1df5be
Revises: c1d507602234
Create Date: 2026-04-23 07:25:00.105242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710a4b1df5be'
down_revision = 'c1d507602234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
