"""enforce non-nullable constraint on 'order' column in 'categories' table, after populating existing records with default values

Revision ID: 735ee6d0fb6a
Revises: ea1a7c221d6b
Create Date: 2026-04-27 12:37:46.049197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735ee6d0fb6a'
down_revision = 'ea1a7c221d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
