"""Make category required

Revision ID: 841832df71bb
Revises: 81dd53f08bac
Create Date: 2026-04-27 11:41:06.158736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841832df71bb'
down_revision = '81dd53f08bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
