"""update recipe model to match the recipe form

Revision ID: c1d507602234
Revises: d7e1644486a8
Create Date: 2026-04-23 07:14:45.865947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d507602234'
down_revision = 'd7e1644486a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_column('cook_time')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cook_time', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
